on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.MY_SECRET }}"
  run-script:
    runs-on: ubuntu-latest
    steps:
      - run: echo "echo Hello World!" > run.sh
      - run: chmod +x ./run.sh
      - run: ./run.sh
      - run: pwd
      - run: ls -la